compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN-''}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.8.5.cjs
