# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: vite-plus setup
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true

      - name: Build
        run: vp run -r build

      - name: Check formatting, linting and type checks.
        run: vp check

      - name: Test unit
        run: vp run -r test

      - name: Test integration esbuild@default
        run: vp run -F example-basic build

      - name: Test integration esbuild@0.12 (minimal)
        run: |
          vp install --filter example-basic esbuild@0.12
          vp run -F example-basic build
